version: '3.9'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"

  api:
    build: .
    container_name: express-api
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
    command: npm start
